In [13]:

import pandas as pd
import os

os.getcwd()
print(os.path.exists("/Users/zu/Desktop/projects/vballPredictor/data/raw/VNL/2021/VNL_Men_Team_2021.csv"))

df = pd.read_csv("/Users/zu/Desktop/projects/vballPredictor/data/raw/VNL/2021/VNL_Men_Team_2021.csv")
df.head()

True

,Season,Match,Y/M/D,Pool,Week,City,Country,Team,VS_Team,SET_Won,...,RECEPTION_Errors,RECEPTION_Attempts,RECEPTION_Total,DIG_Digs,DIG_Errors,DIG_Total,SET_Point,SET_Errors,SET_Attempts,SET_Total
0,2021,1,2021/5/28,1,Preliminary,Rimini,Italy,Bulgaria,France,0,...,4,30,56,9,0,11,3,0,75,78
1,2021,1,2021/5/28,1,Preliminary,Rimini,Italy,Bulgaria,France,0,...,1,10,19,3,0,5,2,0,22,24
2,2021,1,2021/5/28,1,Preliminary,Rimini,Italy,Bulgaria,France,0,...,2,5,17,2,0,2,1,0,22,23
3,2021,1,2021/5/28,1,Preliminary,Rimini,Italy,Bulgaria,France,0,...,1,15,20,4,0,4,0,0,31,31
4,2021,1,2021/5/28,1,Preliminary,Rimini,Italy,France,Bulgaria,3,...,4,26,54,11,0,13,3,1,70,74

In [14]:
df.info

<bound method DataFrame.info of       Season  Match      Y/M/D           Pool          Week    City Country  \
0       2021      1  2021/5/28              1  Preliminary   Rimini   Italy
1       2021      1  2021/5/28              1  Preliminary   Rimini   Italy
2       2021      1  2021/5/28              1  Preliminary   Rimini   Italy
3       2021      1  2021/5/28              1  Preliminary   Rimini   Italy
4       2021      1  2021/5/28              1   Preliminary  Rimini   Italy
...      ...    ...        ...            ...           ...     ...     ...
1167    2021    124  2021/6/27  Final_1st-2nd   Final_Round  Rimini   Italy
1168    2021    124  2021/6/27  Final_1st-2nd   Final_Round  Rimini   Italy
1169    2021    124  2021/6/27  Final_1st-2nd   Final_Round  Rimini   Italy
1170    2021    124  2021/6/27  Final_1st-2nd   Final_Round  Rimini   Italy
1171    2021    124  2021/6/27  Final_1st-2nd   Final_Round  Rimini   Italy

          Team   VS_Team  SET_Won  ...  RECEPTION_Errors  RECEPTION_Attempts  \
0     Bulgaria    France        0  ...                 4                  30
1     Bulgaria    France        0  ...                 1                  10
2     Bulgaria    France        0  ...                 2                   5
3     Bulgaria    France        0  ...                 1                  15
4       France  Bulgaria        3  ...                 4                  26
...        ...       ...      ...  ...               ...                 ...
1167    Poland    Brazil        1  ...                 6                  52
1168    Poland    Brazil        1  ...                 0                  17
1169    Poland    Brazil        1  ...                 2                  10
1170    Poland    Brazil        1  ...                 2                  15
1171    Poland    Brazil        1  ...                 2                  10

      RECEPTION_Total  DIG_Digs DIG_Errors DIG_Total  SET_Point  SET_Errors  \
0                  56         9          0        11          3           0
1                  19         3          0         5          2           0
2                  17         2          0         2          1           0
3                  20         4          0         4          0           0
4                  54        11          0        13          3           1
...               ...       ...        ...       ...        ...         ...
1167               79        31         13        50         24           1
1168               21         9          5        17          5           1
1169               18        10          3        14          5           0
1170               21         6          2        10          4           0
1171               19         6          3         9         10           0

      SET_Attempts SET_Total
0               75        78
1               22        24
2               22        23
3               31        31
4               70        74
...            ...       ...
1167            77       102
1168            24        30
1169            19        24
1170            21        25
1171            13        23

[1172 rows x 50 columns]>

In [15]:
df.shape

(1172, 50)

In [16]:
df.columns

Index(['Season', 'Match', 'Y/M/D', 'Pool', 'Week', 'City', 'Country', 'Team',
       'VS_Team', 'SET_Won', 'SET_Lost', 'Point1', 'Point2', 'Point3',
       'Point4', 'Point5', 'VS_Point1', 'VS_Point2', 'VS_Point3', 'VS_Point4',
       'VS_Point5', 'SET', 'SCORING_Total ABS', 'SCORING_Attack Points',
       'SCORING_Block Points', 'SCORING_Serve Points', 'SCORING_Errors',
       'ATTACK_Point', 'ATTACK_Errors', 'ATTACK_Attempts', 'ATTACK_Total',
       'BLOCK_Point', 'BLOCK_Errors', 'BLOCK_Touches', 'BLOCK_Total',
       'SERVE_Point', 'SERVE_Errors', 'SERVE_Attempts', 'SERVE_Total',
       'RECEPTION_Successful', 'RECEPTION_Errors', 'RECEPTION_Attempts',
       'RECEPTION_Total', 'DIG_Digs', 'DIG_Errors', 'DIG_Total', 'SET_Point',
       'SET_Errors', 'SET_Attempts', 'SET_Total'],
      dtype='object')

In [17]:
df.isnull().sum()

Season                   0
Match                    0
Y/M/D                    0
Pool                     0
Week                     0
City                     0
Country                  0
Team                     0
VS_Team                  0
SET_Won                  0
SET_Lost                 0
Point1                   0
Point2                   0
Point3                   0
Point4                   0
Point5                   0
VS_Point1                0
VS_Point2                0
VS_Point3                0
VS_Point4                0
VS_Point5                0
SET                      0
SCORING_Total ABS        0
SCORING_Attack Points    0
SCORING_Block Points     0
SCORING_Serve Points     0
SCORING_Errors           0
ATTACK_Point             0
ATTACK_Errors            0
ATTACK_Attempts          0
ATTACK_Total             0
BLOCK_Point              0
BLOCK_Errors             0
BLOCK_Touches            0
BLOCK_Total              0
SERVE_Point              0
SERVE_Errors             0
SERVE_Attempts           0
SERVE_Total              0
RECEPTION_Successful     0
RECEPTION_Errors         0
RECEPTION_Attempts       0
RECEPTION_Total          0
DIG_Digs                 0
DIG_Errors               0
DIG_Total                0
SET_Point                0
SET_Errors               0
SET_Attempts             0
SET_Total                0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
df["Team"].unique()

array(['Bulgaria', 'France', 'Australia', 'Germany', 'Iran', 'Japan',
       'Serbia', 'Slovenia', 'Netherlands', 'Russia', 'Canada',
       'United States', 'Italy', 'Poland', 'Argentina', 'Brazil'],
      dtype=object)

In [21]:
df["Y/M/D"] = pd.to_datetime(df["Y/M/D"], format="%Y/%m/%d")

In [22]:
df.dtypes

Season                            int64
Match                             int64
Y/M/D                    datetime64[ns]
Pool                             object
Week                             object
City                             object
Country                          object
Team                             object
VS_Team                          object
SET_Won                           int64
SET_Lost                          int64
Point1                            int64
Point2                            int64
Point3                            int64
Point4                           object
Point5                           object
VS_Point1                         int64
VS_Point2                         int64
VS_Point3                         int64
VS_Point4                        object
VS_Point5                        object
SET                              object
SCORING_Total ABS                 int64
SCORING_Attack Points             int64
SCORING_Block Points              int64
SCORING_Serve Points              int64
SCORING_Errors                   object
ATTACK_Point                      int64
ATTACK_Errors                     int64
ATTACK_Attempts                   int64
ATTACK_Total                      int64
BLOCK_Point                       int64
BLOCK_Errors                      int64
BLOCK_Touches                     int64
BLOCK_Total                       int64
SERVE_Point                       int64
SERVE_Errors                      int64
SERVE_Attempts                    int64
SERVE_Total                       int64
RECEPTION_Successful              int64
RECEPTION_Errors                  int64
RECEPTION_Attempts                int64
RECEPTION_Total                   int64
DIG_Digs                          int64
DIG_Errors                        int64
DIG_Total                         int64
SET_Point                         int64
SET_Errors                        int64
SET_Attempts                      int64
SET_Total                         int64
dtype: object

In [23]:
df = df.drop(columns=["Season", "Match", "Pool", "Week", "City", "Country", ])

In [25]:
df = df[df["SET"] != "ALL"]

In [26]:
df.head()

,Y/M/D,Team,VS_Team,SET_Won,SET_Lost,Point1,Point2,Point3,Point4,Point5,...,RECEPTION_Errors,RECEPTION_Attempts,RECEPTION_Total,DIG_Digs,DIG_Errors,DIG_Total,SET_Point,SET_Errors,SET_Attempts,SET_Total
1,2021-05-28,Bulgaria,France,0,3,25,21,23,-,-,...,1,10,19,3,0,5,2,0,22,24
2,2021-05-28,Bulgaria,France,0,3,25,21,23,-,-,...,2,5,17,2,0,2,1,0,22,23
3,2021-05-28,Bulgaria,France,0,3,25,21,23,-,-,...,1,15,20,4,0,4,0,0,31,31
5,2021-05-28,France,Bulgaria,3,0,27,25,25,-,-,...,3,9,21,7,0,8,2,1,25,28
6,2021-05-28,France,Bulgaria,3,0,27,25,25,-,-,...,0,8,15,2,0,2,0,0,23,23

In [27]:
df.shape

(924, 44)

In [28]:
df = df.drop(columns=["SET"])

In [29]:
df.dtypes

Y/M/D                    datetime64[ns]
Team                             object
VS_Team                          object
SET_Won                           int64
SET_Lost                          int64
Point1                            int64
Point2                            int64
Point3                            int64
Point4                           object
Point5                           object
VS_Point1                         int64
VS_Point2                         int64
VS_Point3                         int64
VS_Point4                        object
VS_Point5                        object
SCORING_Total ABS                 int64
SCORING_Attack Points             int64
SCORING_Block Points              int64
SCORING_Serve Points              int64
SCORING_Errors                   object
ATTACK_Point                      int64
ATTACK_Errors                     int64
ATTACK_Attempts                   int64
ATTACK_Total                      int64
BLOCK_Point                       int64
BLOCK_Errors                      int64
BLOCK_Touches                     int64
BLOCK_Total                       int64
SERVE_Point                       int64
SERVE_Errors                      int64
SERVE_Attempts                    int64
SERVE_Total                       int64
RECEPTION_Successful              int64
RECEPTION_Errors                  int64
RECEPTION_Attempts                int64
RECEPTION_Total                   int64
DIG_Digs                          int64
DIG_Errors                        int64
DIG_Total                         int64
SET_Point                         int64
SET_Errors                        int64
SET_Attempts                      int64
SET_Total                         int64
dtype: object

In [30]:
df.to_csv("/Users/zu/Desktop/projects/vballPredictor/data/processed/cleaned_data.csv", index=False)